### ISSUE TITLE
2266 - GPS connection issue

### ISSUE THREAD

**Issue by almonn** [fhorinek/SkyDrop#159] opened 2016-04-07 09:17 UTC
I loaded 2266 last night, and today on my journey to work experienced some issues.

In short, whilst the GPS acquires, as soon as you move 50~100 metres and go over (say) 5kmh, the GPS signal is lost. 
I can slow down to stopped (or near stopped), and the GPS will then reacquire, but the same problem repeats when you start moving.
I repeated the above start/stop scenario several times at 100metres, 500 metres, 1km, 3km and 8 km intervals, and the behaviour is repeatable (i.e. its not a one-off glitch, it is consistent).
I spotted the issue as the feed to the Kobo/XCsoar would show the message "NO GPS SIGNAL" and the corresponding lack of movement/positional data. It clearly knew the Skydrop was there, as temporarily disconnecting gives a "GPS NOT CONNECTED" message.
I've just got to work, and loaded the Skydrop IGC onto XCplanner, and whilst there is a track, it is a series of straight lines between datapoints of signal and no signal (i.e. the IGC mirrors what I saw on the Kobo/XCSoar unit)

I'll email the IGC and dump/log file

p.s. The test environment is sound. I have used this route repeatedly for two years of testing, the car is simple/old and has no extraneous RF (as proven by previous testing), plus at the mid journey I started up a 2nd Kobo/GPS unit (which has a PA6H GPS; i.e. the same underlying MT3339 chip as the Skydrop) and the 2nd unit behaved fine (i.e. this proves GPS/Satellite system was fine)

**Comment by moyesboy** [comment] 2016-04-07 09:33
This sounds very much like the auto stop/start of the logging somehow malfunctioning and considering your flight to have ended as soon as you exceed 5km/hr.
...except that all the bits of track in the skydrop are in one IGC?
Have you tried some different settings for start/stop?
Perhaps it works great for paragliders flying at only 5km/hr! 
:)

**Comment by almonn** [comment] 2016-04-07 09:34
Stop is set to disabled.

Nev

Date: Thu, 7 Apr 2016 02:33:21 -0700

**Comment by fhorinek** [comment] 2016-04-08 12:52
2266 had wrong gps driver
try this http://vps.skybean.eu/repo/updates/2288/

**Comment by almonn** [comment] 2016-04-08 17:54
Hi Fero
I've done some testing of your pre-release version 2276   (I haven't tried the formal 2288 release yet).
Where there any additional changes from 2276 to 2288?
I'm asking because................ whilst 99.9% of the IGC data is OK (4 drives, total approx 4 hours), the last one did have a 'blip' (where it relocated to the equator for a second or so right at the start), and also the IGC for that one (out of 4) drives has a 1970 datestamp in the header (plus it catalogued in a LOGS directory named 1970 which is how I spotted it!) 

Cheers, Nev

**Comment by fhorinek** [comment] 2016-04-09 07:29
2288 and 2276 share the same code for logging. And the files are ok.
The relocation is caused by not having GPS fix at the start. There are few lines without the GPS fix ant they are marked as invalid. This is normal behavior.

The year 1970 is caused probably by not having time and date set correctly after upgrade. The time is synced automatically when you get your first GPS fix.

But I can see from the log files that the enhancement in the gps diver is working correctly, so in a word SUCCESS!!!

**Closed by fhorinek** 2016-04-09 07:29 UTC
