### ISSUE TITLE
Update 1098

### ISSUE THREAD

**Issue by colignym** [fhorinek/SkyDrop#78] opened 2015-09-07 16:14 UTC
I loaded the update successfully, but it still shows version 910 after reboot, and the screens are blank, and cannot get GPS fix.  When I add a widget like vario, it goes crazy.

**Comment by fhorinek** [comment] 2015-09-07 17:35
Try to revert to 910 and then apply the SKYDROP.FW from http://skybean.eu:8080/repo/updates/1098/

**Comment by colignym** [comment] 2015-09-07 17:43
Did that.  same result.  Did a clean 910.

**Comment by fhorinek** [comment] 2015-09-07 18:04
I was able to replicate this issue but I have to check it at work.
The problem is that somehow the bootloader is not able to reload provided FW. (fast red blink)

Try this:
Put SKYDROP.FW from 1098 and power on vario.
Then when the vario reboot do not power it on from USB mode.
Wait until pc recognize the skydrop as mass storage. 
Remove everything except UPDATE.FW and then press and hold right button.
Repeat the reset procedure until the led is yellow.

**Comment by colignym** [comment] 2015-09-07 18:11
Bit confused, trying to understand the procedure

**Comment by colignym** [comment] 2015-09-07 18:13
oK, that worked,  won't ask how you figured that out.

**Comment by fhorinek** [comment] 2015-09-07 18:27
Simple since I wrote the code :)
The real firmware take place update is AFTER the reboot message.
The update procedure just check the file, update configuration in eeprom and create UPDATE.FW file.
But the bootloader have some problems with sd card (the red blink was a hint).
I would have to figure it why...

**Comment by colignym** [comment] 2015-09-07 19:34
Ok, loaded my sound profile, and the pause and length are perfect, only it gets stuck on one tone frequency, even in demo.  It shows the programmed frequency's, but the sound stays the same.  Then if you go into sink alarm, it changes, but guess what, if you go back to lift, it keeps the sink frequency, even for the menu's.  Tomorrows problem.

**Comment by fhorinek** [comment] 2015-09-07 20:32
provide me the cfg.ee file please
frantisekhorinek@gmail.com

**Comment by fhorinek** [comment] 2015-09-08 08:24
@colignym ok it is fixed in next release

**Comment by IB0S** [comment] 2015-09-08 10:05
Kind of same situation here with 1098 and 1112 also. SkyDrop updated itself only when I plugged the USB out. There was quick red blinking after holding the right button (after copying the update and ejecting the device) and it didn't update. After plugging the USB out, it asked if I want to update.

**Comment by fhorinek** [comment] 2015-09-08 10:10
The update procedure is inside the old firmware so when you apply new SKYDROP.FW the old firmware unpack it and execute it. The situation should change when you use 1112 fw to update to another version (eg. next release or downgrade from 1112 to 1098 or 910)

**Comment by IB0S** [comment] 2015-09-08 10:38
Another thing, it's probably really just me and a dumb question, but it's not clear for me how to manually start/stop flight. I don't know how to understand long pressing in flight time widget. How can I be "in" flight time widget? I've already put it on my preferred screen.

**Comment by fhorinek** [comment] 2015-09-08 10:54
@IB0S same as altitude widget short press of the middle button

**Comment by colignym** [comment] 2015-09-08 10:55
You may have to multiple press until flight time is highlighted, then long press middle button.  Works....but better solutions in the pipeline.

**Comment by IB0S** [comment] 2015-09-08 11:04
Thanks! Just like setting the Alts, don't know how did I miss that.

**Comment by Impactmedien** [comment] 2015-09-11 21:50
Sorry, but i have the same problem with updating from 910 to  1112 or 1098.
I Try this several times:
Put SKYDROP.FW from 1098 and power on vario.
Then when the vario reboot do not power it on from USB mode.
Wait until pc recognize the skydrop as mass storage. 
Remove everything except UPDATE.FW and then press and hold right button.
Repeat the reset procedure until the led is yellow.

I am not sure if there is a problem with fw or your description is not clear. Please what exactly i must do?
From what FW i update? Which files? etc.

**Comment by colignym** [comment] 2015-09-12 09:19
Once you have a clean 910
1) Plug in USB, let it be recognized.  
2) Copy 1098 to Skydrop,
3) Delete cfg file on drop.
4) Long press right button.
5) If you see yellow, that's good.
6) If not, make go back and delete again anything besides FW file, and repeat.

Mine worked.

**Comment by fhorinek** [comment] 2015-09-12 15:06
But do not unplug the cable or exit usb mode

**Comment by Impactmedien** [comment] 2015-09-12 18:00
@colignym thanks. this is a manual ;-)
@fhorinek i tried is now 10 times. the led switch by pressing right button from short red the the drop reboot. then led goes red, blue, green and stay red. on the drop is only FW.

**Comment by colignym** [comment] 2015-09-12 18:13
It is sensitive for exactly the right procedure.

Make sure, on 910, copy the FW from 1098.  Long press  middle button, go through install procedure, but do not unplug the cable.
then do steps 1-6

**Comment by Impactmedien** [comment] 2015-09-12 20:05
Sorry Guys, but the manual for updating is fucking horror. I tried several hours with your manual. PLEASE make a dummy manual for Guys like me. 

This was my way to update and fix the 1098/1112 error

0. fresh 910 FW on SkyDrop - ok, this is a own story

1. Power off SkyDrop
2. connected/mount SkyDrop to pc - SkyDrop will power on to usb mode
3. delete CFG.EE file (or all files?) on SkyDrop 

4. copy 1098/1112 fw to SkyDrop
5. press middle button on SkyDrop
6. apply update on SkyDrop
7. press ok for reboot SkyDrop - SkyDrop will mount again to pc (do not unplug USB Cable)
8. delete CFG.EE file on SkyDrop again - do not delete UPDATE.FW
9. Long press right button.
and hope to see yellow led for a shot time, that's good!  ;-)
10. SkyDrop shows Build 1098/1112 in USB Mode
11. Remove/Demount SkyDrop from PC 
12. pull USB Cabel, SkyDrop will Reboot 
13. Bingo all done.

**Comment by fhorinek** [comment] 2015-09-12 21:08
I know but 1098/1112 are not stable releases.
The 1112 have working single file update (910, 1098 are broken), which is
much more user friendly update method


--
František Horínek

2015-09-12 22:05 GMT+02:00 Impactmedien <notifications@github.com>:

**Comment by colignym** [comment] 2015-09-13 11:48
That's what I meant you should do, but sorry for my bad instructions.  I do not work for skydrop, I am in South Africa.  Skydrop could 1)  Make us wait much longer for stable release, or 2)  give us what they did, and even though it had a few hiccups, I am very happy to have it.

**Comment by Impactmedien** [comment] 2015-09-14 07:44
colignym you are right but it will be fine when we not must write instructions. I updated my post before.

**Comment by colignym** [comment] 2015-09-14 07:58
True, but this project is a work in progress.  We all contribute to make it better.  Writing instructions, is an art in itself, for all to understand.  You certainly did the best job of it, but at the end we all wrote the same instructions, just you made it the best.  
This device is becoming an awesome little instrument!

**Comment by fhorinek** [comment] 2015-10-02 17:37
1098 is now obsolete release, and it is removed from repository. Closin

**Closed by fhorinek** 2015-10-02 17:37 UTC
Labels: bug, question
