### ISSUE TITLE
Build 1278 does not Start

### ISSUE THREAD

**Issue by leachim1** [fhorinek/SkyDrop#96] opened 2015-10-12 19:48 UTC
After flashing the Build 1278 my Skydrop just dont start. The loading screen appears but then it just shut down. When i flash back to 0910 everything works fine.

**Comment by fhorinek** [comment] 2015-10-13 06:48
this can be caused by wrong revision detection.
can you specify the board revision on boot screen and on the pcb?

**Comment by jarda-manana** [comment] 2015-10-13 06:49
both 1504

**Comment by leachim1** [comment] 2015-10-15 18:49
Jeah seems so.
Software: rev 1506.
PCB: rev 1504.

**Comment by fhorinek** [comment] 2015-10-16 07:53
I have reworked the detection a bit, please wait for next beta release and try it again. If ti works please close the issue

**Comment by fhorinek** [comment] 2015-11-03 08:56
@leachim1 did you update the firmware?

**Comment by leachim1** [comment] 2015-11-03 09:10
Jeah, you can close this Bug. THX

**Closed** 2015-11-03 09:22 UTC
Labels: bug
