### ISSUE TITLE
IGC unwanted (and unjustified) IGC recorging start/stop during a single flight

### ISSUE THREAD

**Issue by GeorgesDick** [fhorinek/SkyDrop#185] opened 2016-05-22 07:44 UTC
Yesterday I made a 40 minutes flight, recorded using SkyDrop and an Android app (XC Track).
XC Track recorded a straightforward file from takeoff to landing, but my SkyDrop split this flight in four different files.

To help you debug these unwanted start/stop, please find five files:
2016-05-21-XCT-GDI-01 is the XC Track file
01-0951 + 02-0954 + 03-0955 + 04-1008 are the four "slices" generated by my SkyDrop.

BR,
Georges

[zipfile.zip](https://github.com/fhorinek/SkyDrop/files/276215/zipfile.zip)

**Comment by IB0S** [comment] 2016-05-22 20:49
same here with me today.
false positive landing detections splits flight into several chunks.

**Comment by poletani** [comment] 2016-05-23 13:11
Same problem. The flight was split to 4 IGC files (XC flight 61 km, nearly 3 hrs). 
All IGC files are here [https://www.dropbox.com/s/ni0n3n87m1qctot/21.zip?dl=0](url)
Build 2491

**Comment by fhorinek** [comment] 2016-05-25 12:22
I am sorry but I am unable to recreate the issue. Please try to fly this with this experimental fw with **debug.log on** . Also it have BLE support as a bonus :)

[SKYDROP.FW.zip](https://github.com/fhorinek/SkyDrop/files/281918/SKYDROP.FW.zip)

**Comment by IB0S** [comment] 2016-05-25 12:36
Here's the config I used with (2579): https://drive.google.com/folderview?id=0B-vADa1w0-ryaUwyUzJhM21OOUk&usp=sharing
Also have to mention that I've upgraded to this with the configurator's upgrade function (wich lead/forced me to recreate all the screens this time, not like the upgrades before which kept my screens as they were before.)

**Comment by GeorgesDick** [comment] 2016-05-26 19:56
Thank you for experimental fw, unfortunately I won't be able to try it this week-end: hopefully the next one.

**Comment by IB0S** [comment] 2016-05-27 16:27
> I am sorry but I am unable to recreate the issue. Please try to fly this with this experimental fw with debug.log on . Also it have BLE support as a bonus :)

> 
> SKYDROP.FW.zip
Ok, I've uploaded this fw and enabled debug log. I'll try it out next time and report back.

**Comment by Fulminao** [comment] 2016-05-30 08:45
Same problem with 2579 fw. The flight (about 40 minutes) was split to 2 igc files. I'll upload the experimental fw and next fligh I'll try it.

**Comment by fhorinek** [comment] 2016-05-30 14:12
I found the problem (hopefully), it is hard to confirm it since it is hard to to replicate.
please update and enable debug.log if you want to help with confirmation. 
But the problem is hopefully fixed ... http://vps.skybean.eu/repo/updates/2650/

**Comment by GeorgesDick** [comment] 2016-05-30 15:12
Great! I'll update asap, and (hopefully) give it a try on Saturday.

KR,
Georges

2016-05-30 16:12 GMT+02:00 František Horínek <notifications@github.com>:

> I found the problem (hopefully), it is hard to confirm it since it is hard
> to to replicate.
> please update and enable debug.log if you want to help with confirmation.
> But the problem is hopefully fixed ...
> http://vps.skybean.eu/repo/updates/2650/
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/fhorinek/SkyDrop/issues/185#issuecomment-222501143>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAjLD0F1CHNwNZCRmS6HHl9FRbh4e8k4ks5qGvBrgaJpZM4Ij76O>
> .
>



-- 
Cordialement,

Georges DICK
email georges@monaco.net
http://georgesdick.com

**Comment by IB0S** [comment] 2016-05-30 20:48
> I found the problem (hopefully), it is hard to confirm it since it is hard to to replicate.
please update and enable debug.log if you want to help with confirmation.
But the problem is hopefully fixed ... http://vps.skybean.eu/repo/updates/2650/

Nice to hear!
Well I just flew a little with the 2641 with debug log, split happened again. So here are the log and splits: https://drive.google.com/folderview?id=0B-vADa1w0-ryUWFEbzBtSThfWE0&usp=sharing
I'll try out the new 2650 too soon.

**Comment by fhorinek** [comment] 2016-05-31 06:54
Closing and hoping :)

**Closed by fhorinek** 2016-05-31 06:54 UTC
Labels: bug
