### ISSUE TITLE
1186 - hw revision detection is not working correctly

### ISSUE THREAD

**Issue by jarda-manana** [fhorinek/SkyDrop#86] opened 2015-09-14 15:29 UTC
After upgrade to 1186beta skydrop doesn't start. After power on an empty logo and label build 1186 are shown, red led on. There is no animation of logo and skydrop turns off.
Trying to erase *.EE files, but no success.
Rollback to 1112beta without problems.

**Comment by fhorinek** [comment] 2015-09-14 16:06
This is new. Thank you for the feedback

**Comment by atomphil** [comment] 2015-09-14 17:32
same issue here

**Comment by fhorinek** [comment] 2015-09-14 18:07
can you specify your board version?
you will have to open the drop and look at the number on the bottom

--
František Horínek

2015-09-14 19:32 GMT+02:00 atomphil <notifications@github.com>:

**Comment by atomphil** [comment] 2015-09-14 18:48
drop 1504

**Comment by atomphil** [comment] 2015-09-14 18:49
other side skydrop v1.0

**Comment by SonnenSimon** [comment] 2015-09-14 22:13
almost same for me:
At first after update everything worked - but after applying updated configuration from webconfigurator: Empty logo + red light on.
Bought skydrop 1 week ago..

**Comment by jarda-manana** [comment] 2015-09-15 04:04
drop 1504 for me

**Comment by wunderbaresnet** [comment] 2015-09-16 10:03
Same here. Deleting CONFIG.EE and ejecting then reboots ok, but power off and on won't reboot.

**Comment by jarda-manana** [comment] 2015-09-20 07:45
title changed, thanks @RomanKreisel

**Comment by colignym** [comment] 2015-09-20 13:08
Hi,   please take cognisense of he fact that the Skydrop team is at Coupe icare and that they will only attend to the problems when they are back.  They did forewarn us that this is the case, and the programmer did say that the update is unstable and for those of us that likes to experiment.  I suggest just go back to the previous version to get device working.

**Comment by fhorinek** [comment] 2015-09-21 12:03
![](http://i.ytimg.com/vi/9nXRMgm-7B8/hqdefault.jpg)
...from France

please forget about 1186, the problem is caused by wrong hw revision detection -> i2c is not powered correctly -> sensors are not working -> freeze -> watchdog reboot ...

I will fix the hw revision detection soon

**Comment by fhorinek** [comment] 2015-09-21 13:44
Fixed in next release

**Closed** 2015-09-21 13:44 UTC
Labels: bug
