### ISSUE TITLE
Airspace limit behavior

### ISSUE THREAD

**Issue by eltorio** [fhorinek/SkyDrop#399] opened 2019-07-23 08:13 UTC
Hi,
I activate the air space facility. I do not understand the behavior of the airspace limit widget. The configurator says "Actual maximum and minimum allowed altitude",
I create a screen like this
<img width="668" alt="Capture d’écran 2019-07-23 à 10 11 01" src="https://user-images.githubusercontent.com/6966689/61694683-42ab3f80-ad32-11e9-84cd-585e7bed784f.png">

but I get from my sky drop a message "Inside!"
![IMG_7392](https://user-images.githubusercontent.com/6966689/61694791-81d99080-ad32-11e9-8361-544da7ff05ad.jpg)

**Comment by bubeck** [comment] 2019-07-23 09:07
SkyDrop sees you inside a forbidden airspace at your current position.
Could you please send the GPS position where you tried this? We can then use that position on the airspace database to explain why this happens (or check if it is a bug).

**Comment by eltorio** [comment] 2019-07-29 18:55
This is where i made the test
https://goo.gl/maps/aKSqGuUtrKFb6V9L9

**Comment by bubeck** [comment] 2019-07-30 10:01
This is at 45.826075, 6.724963

```
thorin.wid.bubecks.de  bubeck  …  skydrop  utils  airspace  python3 visualize.py -c 45.826075,6.724963 openaip_airspace_france_fr.aip_1564448518 
[Errno 2] could not open port /dev/ttyUSB1: [Errno 2] No such file or directory: '/dev/ttyUSB1'
No GPS spoofing to SkyDrop...
Point (lat, lon) 45.826075 6.724963
Point (lat, lon) 458260750 67249630
 filename is 'data/N45E006.AIR'
x, y 144 165
offset_point 434475
origin lat 458275000.0
origin lon 67225000.0
lat_offset -3
long_offset 13
otarget lat 45.825302734375
otarget lon 6.732021484375
k -0.23076923076923078
kn 4.333333333333333
  0 102deg    0.561km    mode 1
   i = 37      0 AGL -    300 AGL [RESTRICTED] Contamines 300m/sol
origin lat 458275000.0
origin lon 67225000.0
lat_offset 2
long_offset 8
otarget lat 45.843125
otarget lon 6.785
k 0.25
kn -4.0
  1  75deg    4.986km    mode 0
   i = 42      0 AGL -  11500 MSL [RESTRICTED] R30B interdit PUL
origin lat 458275000.0
origin lon 67225000.0
lat_offset 58
long_offset -52
otarget lat 45.86998046875
otarget lon 6.6844140625
k -1.1153846153846154
kn 0.896551724137931
  2 318deg    5.839km IN mode 1
   i = 33   3000 AGL -  17500 MSL [         E] LTA Mt Blanc 175 Max
origin lat 458275000.0
origin lon 67225000.0
lat_offset 58
long_offset -52
otarget lat 45.86998046875
otarget lon 6.6844140625
k -1.1153846153846154
kn 0.896551724137931
  3 318deg    5.839km    mode 1
   i = 36   3000 AGL -  13500 MSL [         E] LTA Aravis 135 Max
origin lat 458275000.0
origin lon 67225000.0
lat_offset 58
long_offset -52
otarget lat 45.86998046875
otarget lon 6.6844140625
k -1.1153846153846154
kn 0.896551724137931
  4 318deg    5.839km IN mode 1
   i = 39  17500 MSL -  19500 MSL [         D] LTA Mt Blanc


```

**Comment by bubeck** [comment] 2019-07-30 12:50
See https://github.com/fhorinek/SkyDrop/issues/354 for a detailled discussion. The problem is, that you start in a restricted airspace and SkyDrop does not know, if restriction is active or not.

We are working on a confirm/supress method to disable inactive airspaces (or dismiss the alert).
This would mean, that you get a INSIDE alert, that you could dismiss or disable afterwards (until poweroff or something else).

**Comment by ukeconsulting** [comment] 2019-07-30 13:07
:-D 
It's like only people around Mont Blanc are taking care about airspaces 😁

**Comment by bubeck** [comment] 2019-07-30 13:11
Yes. I wondered, whether you know each other. :)

**Comment by ukeconsulting** [comment] 2019-07-30 19:57
we don't know each other, but certainly we fly in same time in same area :-)
and we have the same airspaces problems :-D 
(lot of natural parks and bird restriction zone)

**Comment by eltorio** [comment] 2019-07-31 05:24
Hi,
In fact the test is not in the « Contamines restricted » (90°/0,5km) (natural reserve, always)
Not in the lta mont blanc…
But for the lta mont blanc we need a way to specify the activation wich is only from 1st of july to 31 august. Same each 
I don’t know Romain but sure we fly in the same area😍

**Comment by bubeck** [comment] 2019-10-18 18:40
Check 4820. There is now an option to disable (wrong) airspace warnings.

**Comment by ukeconsulting** [comment] 2019-10-19 12:37
Thanks for this and the alt1 reset ability :-) 

I  updated, just tested at home the airspace filter menu, all seems ok. I checked and understood the manipulation to disable in live and it seems easy.
now i have to go in a restricted area to test in real conditions, sadly i am not near the montblanc nowdays, so not so much restricted area here. it will take some time but for sure i will test it soon.

**Comment by ukeconsulting** [comment] 2019-11-22 11:30
Hi, 

i tested the feature several time and i am not able to desactivate the airspace nor with "forever" button nor with "now" button.

https://youtu.be/xHrGILzTZHM

**Comment by fhorinek** [comment] 2020-01-16 15:51
There was a problem with cache not resetting after the ignore operation. It is fixed now

**Closed by fhorinek** 2020-01-16 15:51 UTC
